import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'mr' | 'hi' | 'te' | 'ml' | 'ta' | 'bn' | 'or';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.programs': 'Programs',
    'nav.impact': 'Our Impact',
    'nav.donate': 'Donate',
    'nav.contact': 'Contact',
    'nav.login': 'Login',
    'nav.chatbot': 'AI Assistant',
    
    // Hero
    'hero.title': 'Empowering Communities,',
    'hero.titleHighlight': 'Transforming Lives',
    'hero.subtitle': 'Join us in creating lasting change through education, healthcare, and sustainable development initiatives.',
    'hero.donate': 'Donate Now',
    'hero.learnMore': 'Learn More',
    
    // Impact
    'impact.title': 'Our Impact',
    'impact.subtitle': 'Making a difference across communities',
    'impact.livesChanged': 'Lives Changed',
    'impact.communities': 'Communities Served',
    'impact.volunteers': 'Active Volunteers',
    'impact.programs': 'Active Programs',
    
    // Programs
    'programs.title': 'Our Programs',
    'programs.subtitle': 'Comprehensive initiatives for sustainable development',
    'programs.education': 'Education',
    'programs.healthcare': 'Healthcare',
    'programs.water': 'Clean Water',
    'programs.emergency': 'Emergency Relief',
    
    // Login
    'login.staff': 'Staff Login',
    'login.donor': 'Donor Login',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.signin': 'Sign In',
    'login.register': 'Register',
    
    // Chatbot
    'chat.title': 'How can I help you today?',
    'chat.placeholder': 'Type your message...',
    'chat.send': 'Send',
    'chat.welcome': 'Hello! I\'m here to help you with any questions about AidConnect Global. How can I assist you today?',
    
    // Footer
    'footer.quickLinks': 'Quick Links',
    'footer.programs': 'Programs',
    'footer.contact': 'Contact Us',
    'footer.newsletter': 'Subscribe to Newsletter',
    'footer.rights': 'All rights reserved',
  },
  mr: {
    'nav.home': 'मुख्यपृष्ठ',
    'nav.about': 'आमच्याबद्दल',
    'nav.programs': 'कार्यक्रम',
    'nav.impact': 'आमचा प्रभाव',
    'nav.donate': 'दान करा',
    'nav.contact': 'संपर्क',
    'nav.login': 'लॉगिन',
    'nav.chatbot': 'AI सहाय्यक',
    'hero.title': 'समुदायांना सक्षम करणे,',
    'hero.titleHighlight': 'जीवन बदलणे',
    'hero.subtitle': 'शिक्षण, आरोग्यसेवा आणि शाश्वत विकास उपक्रमांद्वारे कायमस्वरूपी बदल घडवण्यात आमच्यासोबत सामील व्हा.',
    'hero.donate': 'आता दान करा',
    'hero.learnMore': 'अधिक जाणून घ्या',
    'impact.title': 'आमचा प्रभाव',
    'impact.subtitle': 'समुदायांमध्ये फरक करत आहोत',
    'impact.livesChanged': 'बदललेली जीवने',
    'impact.communities': 'सेवा दिलेले समुदाय',
    'impact.volunteers': 'सक्रिय स्वयंसेवक',
    'impact.programs': 'सक्रिय कार्यक्रम',
    'programs.title': 'आमचे कार्यक्रम',
    'programs.subtitle': 'शाश्वत विकासासाठी सर्वसमावेशक उपक्रम',
    'programs.education': 'शिक्षण',
    'programs.healthcare': 'आरोग्यसेवा',
    'programs.water': 'स्वच्छ पाणी',
    'programs.emergency': 'आपत्कालीन मदत',
    'login.staff': 'कर्मचारी लॉगिन',
    'login.donor': 'दाता लॉगिन',
    'login.email': 'ईमेल पत्ता',
    'login.password': 'पासवर्ड',
    'login.signin': 'साइन इन',
    'login.register': 'नोंदणी करा',
    'chat.title': 'आज मी तुम्हाला कसे मदत करू?',
    'chat.placeholder': 'तुमचा संदेश टाइप करा...',
    'chat.send': 'पाठवा',
    'chat.welcome': 'नमस्कार! AidConnect Global बद्दल कोणत्याही प्रश्नांसाठी मी येथे मदत करण्यासाठी आहे. आज मी तुम्हाला कशी मदत करू शकतो?',
    'footer.quickLinks': 'जलद दुवे',
    'footer.programs': 'कार्यक्रम',
    'footer.contact': 'संपर्क साधा',
    'footer.newsletter': 'वृत्तपत्रासाठी सदस्यता घ्या',
    'footer.rights': 'सर्व हक्क राखीव',
  },
  hi: {
    'nav.home': 'होम',
    'nav.about': 'हमारे बारे में',
    'nav.programs': 'कार्यक्रम',
    'nav.impact': 'हमारा प्रभाव',
    'nav.donate': 'दान करें',
    'nav.contact': 'संपर्क',
    'nav.login': 'लॉगिन',
    'nav.chatbot': 'AI सहायक',
    'hero.title': 'समुदायों को सशक्त बनाना,',
    'hero.titleHighlight': 'जीवन बदलना',
    'hero.subtitle': 'शिक्षा, स्वास्थ्य और सतत विकास पहलों के माध्यम से स्थायी परिवर्तन लाने में हमारे साथ जुड़ें।',
    'hero.donate': 'अभी दान करें',
    'hero.learnMore': 'और जानें',
    'impact.title': 'हमारा प्रभाव',
    'impact.subtitle': 'समुदायों में बदलाव ला रहे हैं',
    'impact.livesChanged': 'बदले गए जीवन',
    'impact.communities': 'सेवित समुदाय',
    'impact.volunteers': 'सक्रिय स्वयंसेवक',
    'impact.programs': 'सक्रिय कार्यक्रम',
    'programs.title': 'हमारे कार्यक्रम',
    'programs.subtitle': 'सतत विकास के लिए व्यापक पहल',
    'programs.education': 'शिक्षा',
    'programs.healthcare': 'स्वास्थ्य',
    'programs.water': 'स्वच्छ जल',
    'programs.emergency': 'आपातकालीन राहत',
    'login.staff': 'स्टाफ लॉगिन',
    'login.donor': 'दाता लॉगिन',
    'login.email': 'ईमेल पता',
    'login.password': 'पासवर्ड',
    'login.signin': 'साइन इन',
    'login.register': 'रजिस्टर करें',
    'chat.title': 'आज मैं आपकी कैसे मदद कर सकता हूं?',
    'chat.placeholder': 'अपना संदेश टाइप करें...',
    'chat.send': 'भेजें',
    'chat.welcome': 'नमस्ते! AidConnect Global के बारे में किसी भी प्रश्न में मदद के लिए मैं यहां हूं। आज मैं आपकी कैसे सहायता कर सकता हूं?',
    'footer.quickLinks': 'त्वरित लिंक',
    'footer.programs': 'कार्यक्रम',
    'footer.contact': 'संपर्क करें',
    'footer.newsletter': 'न्यूज़लेटर सदस्यता',
    'footer.rights': 'सर्वाधिकार सुरक्षित',
  },
  te: {
    'nav.home': 'హోమ్',
    'nav.about': 'మా గురించి',
    'nav.programs': 'కార్యక్రమాలు',
    'nav.impact': 'మా ప్రభావం',
    'nav.donate': 'విరాళం',
    'nav.contact': 'సంప్రదించండి',
    'nav.login': 'లాగిన్',
    'nav.chatbot': 'AI సహాయకుడు',
    'hero.title': 'సమాజాలను శక్తివంతం చేయడం,',
    'hero.titleHighlight': 'జీవితాలను మార్చడం',
    'hero.subtitle': 'విద్య, ఆరోగ్య సంరక్షణ మరియు సుస్థిర అభివృద్ధి కార్యక్రమాల ద్వారా శాశ్వత మార్పు సృష్టించడంలో మాతో చేరండి.',
    'hero.donate': 'ఇప్పుడు విరాళం ఇవ్వండి',
    'hero.learnMore': 'మరింత తెలుసుకోండి',
    'impact.title': 'మా ప్రభావం',
    'impact.subtitle': 'సమాజాలలో మార్పు తీసుకురావడం',
    'impact.livesChanged': 'మార్చిన జీవితాలు',
    'impact.communities': 'సేవించిన సమాజాలు',
    'impact.volunteers': 'క్రియాశీల వలంటీర్లు',
    'impact.programs': 'క్రియాశీల కార్యక్రమాలు',
    'programs.title': 'మా కార్యక్రమాలు',
    'programs.subtitle': 'సుస్థిర అభివృద్ధికి సమగ్ర కార్యక్రమాలు',
    'programs.education': 'విద్య',
    'programs.healthcare': 'ఆరోగ్య సంరక్షణ',
    'programs.water': 'శుద్ధమైన నీరు',
    'programs.emergency': 'అత్యవసర సహాయం',
    'login.staff': 'సిబ్బంది లాగిన్',
    'login.donor': 'దాత లాగిన్',
    'login.email': 'ఇమెయిల్ చిరునామా',
    'login.password': 'పాస్‌వర్డ్',
    'login.signin': 'సైన్ ఇన్',
    'login.register': 'నమోదు',
    'chat.title': 'ఈ రోజు నేను మీకు ఎలా సహాయం చేయగలను?',
    'chat.placeholder': 'మీ సందేశాన్ని టైప్ చేయండి...',
    'chat.send': 'పంపండి',
    'chat.welcome': 'హలో! AidConnect Global గురించి ఏవైనా ప్రశ్నలకు సహాయం చేయడానికి నేను ఇక్కడ ఉన్నాను. ఈ రోజు నేను మీకు ఎలా సహాయం చేయగలను?',
    'footer.quickLinks': 'త్వరిత లింక్‌లు',
    'footer.programs': 'కార్యక్రమాలు',
    'footer.contact': 'సంప్రదించండి',
    'footer.newsletter': 'వార్తాలేఖకు సభ్యత్వం',
    'footer.rights': 'అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి',
  },
  ml: {
    'nav.home': 'ഹോം',
    'nav.about': 'ഞങ്ങളെക്കുറിച്ച്',
    'nav.programs': 'പ്രോഗ്രാമുകൾ',
    'nav.impact': 'ഞങ്ങളുടെ സ്വാധീനം',
    'nav.donate': 'സംഭാവന',
    'nav.contact': 'ബന്ധപ്പെടുക',
    'nav.login': 'ലോഗിൻ',
    'nav.chatbot': 'AI സഹായി',
    'hero.title': 'സമൂഹങ്ങളെ ശാക്തീകരിക്കുന്നു,',
    'hero.titleHighlight': 'ജീവിതങ്ങൾ മാറ്റുന്നു',
    'hero.subtitle': 'വിദ്യാഭ്യാസം, ആരോഗ്യ പരിരക്ഷ, സുസ്ഥിര വികസന സംരംഭങ്ങളിലൂടെ ശാശ്വത മാറ്റം സൃഷ്ടിക്കാൻ ഞങ്ങളോടൊപ്പം ചേരുക.',
    'hero.donate': 'ഇപ്പോൾ സംഭാവന ചെയ്യുക',
    'hero.learnMore': 'കൂടുതൽ അറിയുക',
    'impact.title': 'ഞങ്ങളുടെ സ്വാധീനം',
    'impact.subtitle': 'സമൂഹങ്ങളിൽ മാറ്റം വരുത്തുന്നു',
    'impact.livesChanged': 'മാറ്റിയ ജീവിതങ്ങൾ',
    'impact.communities': 'സേവിച്ച സമൂഹങ്ങൾ',
    'impact.volunteers': 'സജീവ വോളണ്ടിയർമാർ',
    'impact.programs': 'സജീവ പ്രോഗ്രാമുകൾ',
    'programs.title': 'ഞങ്ങളുടെ പ്രോഗ്രാമുകൾ',
    'programs.subtitle': 'സുസ്ഥിര വികസനത്തിനായുള്ള സമഗ്ര സംരംഭങ്ങൾ',
    'programs.education': 'വിദ്യാഭ്യാസം',
    'programs.healthcare': 'ആരോഗ്യ പരിരക്ഷ',
    'programs.water': 'ശുദ്ധജലം',
    'programs.emergency': 'അടിയന്തര സഹായം',
    'login.staff': 'സ്റ്റാഫ് ലോഗിൻ',
    'login.donor': 'ദാതാവ് ലോഗിൻ',
    'login.email': 'ഇമെയിൽ വിലാസം',
    'login.password': 'പാസ്‌വേഡ്',
    'login.signin': 'സൈൻ ഇൻ',
    'login.register': 'രജിസ്റ്റർ',
    'chat.title': 'ഇന്ന് ഞാൻ നിങ്ങളെ എങ്ങനെ സഹായിക്കും?',
    'chat.placeholder': 'നിങ്ങളുടെ സന്ദേശം ടൈപ്പ് ചെയ്യുക...',
    'chat.send': 'അയയ്ക്കുക',
    'chat.welcome': 'ഹലോ! AidConnect Global-നെക്കുറിച്ചുള്ള ഏത് ചോദ്യങ്ങൾക്കും സഹായിക്കാൻ ഞാൻ ഇവിടെയുണ്ട്. ഇന്ന് ഞാൻ നിങ്ങളെ എങ്ങനെ സഹായിക്കും?',
    'footer.quickLinks': 'ദ്രുത ലിങ്കുകൾ',
    'footer.programs': 'പ്രോഗ്രാമുകൾ',
    'footer.contact': 'ബന്ധപ്പെടുക',
    'footer.newsletter': 'വാർത്താക്കുറിപ്പ് സബ്സ്ക്രൈബ്',
    'footer.rights': 'എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തമാണ്',
  },
  ta: {
    'nav.home': 'முகப்பு',
    'nav.about': 'எங்களைப் பற்றி',
    'nav.programs': 'திட்டங்கள்',
    'nav.impact': 'எங்கள் தாக்கம்',
    'nav.donate': 'நன்கொடை',
    'nav.contact': 'தொடர்பு',
    'nav.login': 'உள்நுழைவு',
    'nav.chatbot': 'AI உதவியாளர்',
    'hero.title': 'சமூகங்களை வலுப்படுத்துதல்,',
    'hero.titleHighlight': 'வாழ்க்கையை மாற்றுதல்',
    'hero.subtitle': 'கல்வி, சுகாதாரம் மற்றும் நிலையான வளர்ச்சி முயற்சிகள் மூலம் நிலையான மாற்றத்தை உருவாக்க எங்களுடன் இணையுங்கள்.',
    'hero.donate': 'இப்போது நன்கொடை அளியுங்கள்',
    'hero.learnMore': 'மேலும் அறிக',
    'impact.title': 'எங்கள் தாக்கம்',
    'impact.subtitle': 'சமூகங்களில் மாற்றத்தை ஏற்படுத்துகிறோம்',
    'impact.livesChanged': 'மாற்றப்பட்ட வாழ்க்கைகள்',
    'impact.communities': 'சேவை செய்த சமூகங்கள்',
    'impact.volunteers': 'செயலில் உள்ள தன்னார்வலர்கள்',
    'impact.programs': 'செயலில் உள்ள திட்டங்கள்',
    'programs.title': 'எங்கள் திட்டங்கள்',
    'programs.subtitle': 'நிலையான வளர்ச்சிக்கான விரிவான முயற்சிகள்',
    'programs.education': 'கல்வி',
    'programs.healthcare': 'சுகாதாரம்',
    'programs.water': 'சுத்தமான நீர்',
    'programs.emergency': 'அவசர நிவாரணம்',
    'login.staff': 'ஊழியர் உள்நுழைவு',
    'login.donor': 'நன்கொடையாளர் உள்நுழைவு',
    'login.email': 'மின்னஞ்சல் முகவரி',
    'login.password': 'கடவுச்சொல்',
    'login.signin': 'உள்நுழைக',
    'login.register': 'பதிவு செய்க',
    'chat.title': 'இன்று நான் உங்களுக்கு எப்படி உதவ முடியும்?',
    'chat.placeholder': 'உங்கள் செய்தியை தட்டச்சு செய்யுங்கள்...',
    'chat.send': 'அனுப்பு',
    'chat.welcome': 'வணக்கம்! AidConnect Global பற்றிய எந்த கேள்விகளுக்கும் உதவ நான் இங்கே இருக்கிறேன். இன்று நான் உங்களுக்கு எப்படி உதவ முடியும்?',
    'footer.quickLinks': 'விரைவு இணைப்புகள்',
    'footer.programs': 'திட்டங்கள்',
    'footer.contact': 'தொடர்பு கொள்ளுங்கள்',
    'footer.newsletter': 'செய்திமடல் சந்தா',
    'footer.rights': 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை',
  },
  bn: {
    'nav.home': 'হোম',
    'nav.about': 'আমাদের সম্পর্কে',
    'nav.programs': 'প্রোগ্রাম',
    'nav.impact': 'আমাদের প্রভাব',
    'nav.donate': 'দান করুন',
    'nav.contact': 'যোগাযোগ',
    'nav.login': 'লগইন',
    'nav.chatbot': 'AI সহায়ক',
    'hero.title': 'সম্প্রদায়কে ক্ষমতায়ন,',
    'hero.titleHighlight': 'জীবন পরিবর্তন',
    'hero.subtitle': 'শিক্ষা, স্বাস্থ্যসেবা এবং টেকসই উন্নয়ন উদ্যোগের মাধ্যমে স্থায়ী পরিবর্তন তৈরিতে আমাদের সাথে যোগ দিন।',
    'hero.donate': 'এখনই দান করুন',
    'hero.learnMore': 'আরও জানুন',
    'impact.title': 'আমাদের প্রভাব',
    'impact.subtitle': 'সম্প্রদায়ে পরিবর্তন আনছি',
    'impact.livesChanged': 'পরিবর্তিত জীবন',
    'impact.communities': 'সেবিত সম্প্রদায়',
    'impact.volunteers': 'সক্রিয় স্বেচ্ছাসেবক',
    'impact.programs': 'সক্রিয় প্রোগ্রাম',
    'programs.title': 'আমাদের প্রোগ্রাম',
    'programs.subtitle': 'টেকসই উন্নয়নের জন্য ব্যাপক উদ্যোগ',
    'programs.education': 'শিক্ষা',
    'programs.healthcare': 'স্বাস্থ্যসেবা',
    'programs.water': 'পরিষ্কার পানি',
    'programs.emergency': 'জরুরি সাহায্য',
    'login.staff': 'কর্মী লগইন',
    'login.donor': 'দাতা লগইন',
    'login.email': 'ইমেইল ঠিকানা',
    'login.password': 'পাসওয়ার্ড',
    'login.signin': 'সাইন ইন',
    'login.register': 'নিবন্ধন',
    'chat.title': 'আজ আমি কীভাবে আপনাকে সাহায্য করতে পারি?',
    'chat.placeholder': 'আপনার বার্তা টাইপ করুন...',
    'chat.send': 'পাঠান',
    'chat.welcome': 'হ্যালো! AidConnect Global সম্পর্কে যেকোনো প্রশ্নে সাহায্য করতে আমি এখানে আছি। আজ আমি কীভাবে আপনাকে সাহায্য করতে পারি?',
    'footer.quickLinks': 'দ্রুত লিঙ্ক',
    'footer.programs': 'প্রোগ্রাম',
    'footer.contact': 'যোগাযোগ করুন',
    'footer.newsletter': 'নিউজলেটার সাবস্ক্রাইব',
    'footer.rights': 'সর্বস্বত্ব সংরক্ষিত',
  },
  or: {
    'nav.home': 'ହୋମ୍',
    'nav.about': 'ଆମ ବିଷୟରେ',
    'nav.programs': 'କାର୍ଯ୍ୟକ୍ରମ',
    'nav.impact': 'ଆମର ପ୍ରଭାବ',
    'nav.donate': 'ଦାନ',
    'nav.contact': 'ଯୋଗାଯୋଗ',
    'nav.login': 'ଲଗଇନ୍',
    'nav.chatbot': 'AI ସହାୟକ',
    'hero.title': 'ସମୁଦାୟକୁ ସଶକ୍ତ କରିବା,',
    'hero.titleHighlight': 'ଜୀବନ ବଦଳାଇବା',
    'hero.subtitle': 'ଶିକ୍ଷା, ସ୍ୱାସ୍ଥ୍ୟସେବା ଏବଂ ସ୍ଥାୟୀ ବିକାଶ ଉଦ୍ୟମ ମାଧ୍ୟମରେ ସ୍ଥାୟୀ ପରିବର୍ତ୍ତନ ସୃଷ୍ଟି କରିବାରେ ଆମ ସହିତ ଯୋଗ ଦିଅନ୍ତୁ।',
    'hero.donate': 'ବର୍ତ୍ତମାନ ଦାନ କରନ୍ତୁ',
    'hero.learnMore': 'ଅଧିକ ଜାଣନ୍ତୁ',
    'impact.title': 'ଆମର ପ୍ରଭାବ',
    'impact.subtitle': 'ସମୁଦାୟରେ ପରିବର୍ତ୍ତନ ଆଣୁଛୁ',
    'impact.livesChanged': 'ବଦଳାଯାଇଥିବା ଜୀବନ',
    'impact.communities': 'ସେବା ଦିଆଯାଇଥିବା ସମୁଦାୟ',
    'impact.volunteers': 'ସକ୍ରିୟ ସ୍ୱେଚ୍ଛାସେବୀ',
    'impact.programs': 'ସକ୍ରିୟ କାର୍ଯ୍ୟକ୍ରମ',
    'programs.title': 'ଆମର କାର୍ଯ୍ୟକ୍ରମ',
    'programs.subtitle': 'ସ୍ଥାୟୀ ବିକାଶ ପାଇଁ ବ୍ୟାପକ ଉଦ୍ୟମ',
    'programs.education': 'ଶିକ୍ଷା',
    'programs.healthcare': 'ସ୍ୱାସ୍ଥ୍ୟସେବା',
    'programs.water': 'ପରିଷ୍କାର ପାଣି',
    'programs.emergency': 'ଜରୁରୀକାଳୀନ ସାହାଯ୍ୟ',
    'login.staff': 'କର୍ମଚାରୀ ଲଗଇନ୍',
    'login.donor': 'ଦାତା ଲଗଇନ୍',
    'login.email': 'ଇମେଲ୍ ଠିକଣା',
    'login.password': 'ପାସୱାର୍ଡ',
    'login.signin': 'ସାଇନ୍ ଇନ୍',
    'login.register': 'ପଞ୍ଜୀକରଣ',
    'chat.title': 'ଆଜି ମୁଁ ଆପଣଙ୍କୁ କିପରି ସାହାଯ୍ୟ କରିପାରିବି?',
    'chat.placeholder': 'ଆପଣଙ୍କ ବାର୍ତ୍ତା ଟାଇପ୍ କରନ୍ତୁ...',
    'chat.send': 'ପଠାନ୍ତୁ',
    'chat.welcome': 'ନମସ୍କାର! AidConnect Global ବିଷୟରେ ଯେକୌଣସି ପ୍ରଶ୍ନରେ ସାହାଯ୍ୟ କରିବାକୁ ମୁଁ ଏଠାରେ ଅଛି। ଆଜି ମୁଁ ଆପଣଙ୍କୁ କିପରି ସାହାଯ୍ୟ କରିପାରିବି?',
    'footer.quickLinks': 'ଦ୍ରୁତ ଲିଙ୍କ',
    'footer.programs': 'କାର୍ଯ୍ୟକ୍ରମ',
    'footer.contact': 'ଯୋଗାଯୋଗ କରନ୍ତୁ',
    'footer.newsletter': 'ନ୍ୟୁଜଲେଟର ସବ୍ସକ୍ରାଇବ୍',
    'footer.rights': 'ସମସ୍ତ ଅଧିକାର ସଂରକ୍ଷିତ',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const stored = localStorage.getItem('aidconnect-language') as Language;
    if (stored && translations[stored]) {
      setLanguageState(stored);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('aidconnect-language', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
